/**
 * @fileoverview Session types - Complete type definitions for session management.
 *
 * Based on OpenCode's session architecture with support for:
 * - Full Part types (text, reasoning, file, tool, step-start, step-finish)
 * - Parent-child session relationships
 * - Message history with 100 message limit
 * - Compaction interface (for future implementation)
 */

export type Role = "user" | "assistant" | "system" | "tool" | "agent";

/**
 * Session metadata and configuration.
 */
export interface SessionInfo {
  /** Unique session identifier (e.g., ses_abc123) */
  id: string;
  /** Parent session ID for child sessions */
  parentID?: string;
  /** Session title */
  title: string;
  /** Working directory */
  directory: string;
  /** File change summary */
  summary?: {
    additions: number;
    deletions: number;
    files: number;
  };
  /** Timestamps */
  time: {
    created: number;
    updated: number;
    /** Compaction timestamp (reserved for future use) */
    compacting?: number;
  };
  /** Additional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Message metadata.
 */
export interface MessageInfo {
  /** Unique message identifier (e.g., msg_abc123) */
  id: string;
  /** Associated session ID */
  sessionID: string;
  /** Parent message ID for threaded replies */
  parentID?: string;
  /** Message role */
  role: Role;
  /** Agent name */
  agent?: string;
  /** Model identifier */
  model?: string;
  /** Creation timestamp */
  timestamp: number;
  /** Additional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Base interface for all Part types.
 */
interface PartBase {
  /** Unique part identifier (e.g., prt_abc123) */
  id: string;
}

/**
 * Text content part.
 */
export interface TextPart extends PartBase {
  type: "text";
  text: string;
  /** If true, this part should be ignored in the conversation */
  ignored?: boolean;
  /** If true, this part was generated by the system */
  synthetic?: boolean;
  time?: { start: number; end?: number };
}

/**
 * AI reasoning/thought content part.
 * This part contains the AI's thinking process.
 */
export interface ReasoningPart extends PartBase {
  type: "reasoning";
  text: string;
  metadata?: Record<string, unknown>;
  time: { start: number; end?: number };
}

/**
 * File attachment part.
 */
export interface FilePart extends PartBase {
  type: "file";
  /** MIME type */
  mime: string;
  /** Original filename */
  filename?: string;
  /** File URL or path */
  url: string;
}

/**
 * Tool call result part.
 */
export interface ToolPart extends PartBase {
  type: "tool";
  /** Unique tool call ID */
  callID: string;
  /** Tool name */
  tool: string;
  /** Current execution state */
  state: "pending" | "running" | "completed" | "error";
  /** Tool input arguments */
  input: Record<string, unknown>;
  /** Tool output (when completed) */
  output?: string;
  /** Error message (when error) */
  error?: string;
  /** Additional metadata */
  metadata?: Record<string, unknown>;
  time?: { start: number; end?: number };
}

/**
 * Step start marker part.
 */
export interface StepStartPart extends PartBase {
  type: "step-start";
}

/**
 * Step finish marker part.
 */
export interface StepFinishPart extends PartBase {
  type: "step-finish";
  /** Reason for finishing */
  reason: string;
}

/**
 * Compaction marker part.
 */
export interface CompactionPart extends PartBase {
  type: "compaction";
  summary: string;
  removed_messages: number;
}

/**
 * Subtask marker part.
 */
export interface SubtaskPart extends PartBase {
  type: "subtask";
  task_id: string;
}

/** Union type for all Part types. */
export type Part = TextPart | ReasoningPart | FilePart | ToolPart | StepStartPart | StepFinishPart | CompactionPart | SubtaskPart;

/**
 * Message with all its parts.
 */
export interface MessageWithParts {
  info: MessageInfo;
  parts: Part[];
}

/**
 * Multimodal message content types.
 * Supports text, images, audio, and other content types.
 */
export type MessageContent = 
  | TextContent
  | ImageContent
  | AudioContent
  | FileContent;

/**
 * Text content - plain text.
 */
export interface TextContent {
  type: "text";
  text: string;
}

/**
 * Image content - either URL or base64 encoded data.
 */
export interface ImageContent {
  type: "image";
  /** URL to the image or base64 data URI */
  image: string;
  /** MIME type of the image */
  mimeType?: string;
}

/**
 * Audio content - URL or base64 encoded audio data.
 */
export interface AudioContent {
  type: "audio";
  /** URL to the audio or base64 data URI */
  audio: string;
  /** MIME type of the audio */
  mimeType?: string;
}

/**
 * Generic file content - for other file types.
 */
export interface FileContent {
  type: "file";
  /** URL or path to the file */
  url: string;
  /** MIME type of the file */
  mimeType: string;
  /** Optional filename */
  filename?: string;
}

/**
 * History message format for Agent Core.
 * Supports multimodal content (text, images, audio, files).
 * Compatible with the handle_query history parameter.
 */
export interface HistoryMessage {
  role: "system" | "user" | "assistant" | "tool";
  content: MessageContent | MessageContent[];
  name?: string;
  tool_call_id?: string;
}

/**
 * Simple text-only history message (backward compatible).
 */
export interface SimpleHistoryMessage {
  role: "system" | "user" | "assistant" | "tool";
  content: string;
  name?: string;
}

/**
 * Session creation options.
 */
export interface SessionCreateOptions {
  /** Session ID (optional, auto-generated if not provided) */
  id?: string;
  /** Parent session ID for child sessions */
  parentID?: string;
  /** Session title */
  title?: string;
  /** Working directory */
  directory?: string;
  /** Additional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Message creation options.
 */
export interface MessageCreateOptions {
  role: Role;
  content: string;
  agent?: string;
  model?: string;
  metadata?: Record<string, unknown>;
}
